export const ACTION = {
  CONTACTS_CLEARED: "CONTACTS_CLEARED_FROM_OPTIONS",
  CSV_DATA_PARSED: "CSV_DATA_PARSED_FROM_OPTIONS",
  FORM_SUBMITTED: "FORM_SUBMITTED",
  ERROR: "ERROR"
};

export const STORAGE_KEYS = {
  MESSAGE_TEMPLATE: "MESSAGE_TEMPLATE",
  CSV_CONTACTS: "CSV_CONTACTS"
};